name: Daily Cron Job

on:
  schedule:
    - cron: '0 7 * * *'  # 每天早上 7 点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 确保你有一个 requirements.txt 文件

      - name: Run Script
        run: python3 your_script.py

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: output-results
          path: output/  # 指定你的输出文件夹
